### ISSUE TITLE
请问如何驱动指纹和摄像头？

### ISSUE THREAD

**Issue by Undifinedu** [jieelin/XPS9370-Hackintosh#9]
我的机器是无触屏版本的9370，直接用您的clover无法开机。
用您的config.plist和kext及acpi的patch顺利使系统跑起来了，但是发现摄像头及指纹无法使用，想咨询有什么解决办法。
PS:系统为10.15.3。附件为目前使用的clover
[CLOVER.zip](https://github.com/jieelin/XPS9370-Hackintosh/files/4332210/CLOVER.zip)

**Comment by jieelin** [comment]
暂时除了苹果，没有其它的机子黑苹果后可以正常使用指纹的。。
我的机子，使用的是10.14.3的系统，安装时已经直接识别出摄像头了。。

**Comment by Undifinedu** [comment]
谢谢，我翻了下其他的帖子，可能就是后面系统都没法识别。
